# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T17:54:26+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyQuery, BaseSecurity
from fastapi import Header
from pydantic import conint

from models import (
    Artifacts,
    Build,
    BuildDetail,
    Builds,
    BuildSummary,
    ContentType,
    Envvar,
    Envvars,
    Filter,
    Key,
    Keys,
    Projects,
    ProjectUsernameProjectBuildCacheDeleteResponse,
    ProjectUsernameProjectCheckoutKeyFingerprintDeleteResponse,
    ProjectUsernameProjectCheckoutKeyPostRequest,
    ProjectUsernameProjectEnvvarNameDeleteResponse,
    ProjectUsernameProjectPostRequest,
    ProjectUsernameProjectSshKeyPostRequest,
    ProjectUsernameProjectSshKeyPostResponse,
    ProjectUsernameProjectTreeBranchPostRequest,
    Tests,
    User,
    UserHerokuKeyPostResponse,
)

app = MCPProxy(
    description='The CircleCI API is a RESTful, fully-featured API that allows you to do almost anything in CircleCI.\nYou can access all information and trigger all actions.\nThe only thing we don’t provide access to is billing functions, which must be done from the CircleCI web UI.\n',
    license={
        'name': 'Attribution-NonCommercial-ShareAlike 4.0 International',
        'url': 'http://creativecommons.org/licenses/by-nc-sa/4.0/',
    },
    title='CircleCI REST API',
    version='v1',
    servers=[{'url': 'https://circleci.com/api/v1'}],
)


@app.get(
    '/me',
    description=""" Provides information about the signed in user.
 """,
    tags=['user_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def get_me():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/project/{username}/{project}',
    description=""" Build summary for each of the last 30 builds for a single git repo.
 """,
    tags=['user_management', 'project_data_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def get_project__username__project(
    limit: Optional[conint(le=100)] = 30,
    offset: Optional[int] = 0,
    filter: Optional[Filter] = None,
    username: str = ...,
    project: str = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/project/{username}/{project}',
    description=""" Triggers a new build, returns a summary of the build.
 """,
    tags=['user_management', 'project_data_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def post_project__username__project(
    username: str, project: str = ..., body: ProjectUsernameProjectPostRequest = None
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/project/{username}/{project}/build-cache',
    description=""" Clears the cache for a project.
 """,
    tags=['user_management', 'project_data_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def delete_project__username__project_build_cache(username: str, project: str = ...):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/project/{username}/{project}/checkout-key',
    description=""" Lists checkout keys.
 """,
    tags=['user_management', 'project_data_management', 'checkout_key_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def get_project__username__project_checkout_key(username: str, project: str = ...):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/project/{username}/{project}/checkout-key',
    description=""" Creates a new checkout key.
Only usable with a user API token.
 """,
    tags=['checkout_key_management', 'project_data_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def post_project__username__project_checkout_key(
    username: str,
    project: str = ...,
    body: ProjectUsernameProjectCheckoutKeyPostRequest = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/project/{username}/{project}/checkout-key/{fingerprint}',
    description=""" Delete a checkout key.
 """,
    tags=['user_management', 'project_data_management', 'checkout_key_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def delete_project__username__project_checkout_key__fingerprint(
    username: str, project: str = ..., fingerprint: str = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/project/{username}/{project}/checkout-key/{fingerprint}',
    description=""" Get a checkout key.
 """,
    tags=['user_management', 'project_data_management', 'checkout_key_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def get_project__username__project_checkout_key__fingerprint(
    username: str, project: str = ..., fingerprint: str = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/project/{username}/{project}/envvar',
    description=""" Lists the environment variables for :project
 """,
    tags=['user_management', 'project_data_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def get_project__username__project_envvar(username: str, project: str = ...):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/project/{username}/{project}/envvar',
    description=""" Creates a new environment variable
 """,
    tags=['user_management', 'project_data_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def post_project__username__project_envvar(username: str, project: str = ...):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/project/{username}/{project}/envvar/{name}',
    description=""" Deletes the environment variable named ':name'
 """,
    tags=['user_management', 'project_data_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def delete_project__username__project_envvar__name(
    username: str, project: str = ..., name: str = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/project/{username}/{project}/envvar/{name}',
    description=""" Gets the hidden value of environment variable :name
 """,
    tags=['user_management', 'project_data_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def get_project__username__project_envvar__name(
    username: str, project: str = ..., name: str = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/project/{username}/{project}/ssh-key',
    description=""" Create an ssh key used to access external systems that require SSH key-based authentication
 """,
    tags=['user_management', 'checkout_key_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def post_project__username__project_ssh_key(
    content__type: ContentType = Header(..., alias='Content-Type'),
    username: str = ...,
    project: str = ...,
    body: ProjectUsernameProjectSshKeyPostRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/project/{username}/{project}/tree/{branch}',
    description=""" Triggers a new build, returns a summary of the build.
Optional build parameters can be set using an experimental API.

Note: For more about build parameters, read about [using parameterized builds](https://circleci.com/docs/parameterized-builds/)
 """,
    tags=['project_data_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def post_project__username__project_tree__branch(
    username: str,
    project: str = ...,
    branch: str = ...,
    body: ProjectUsernameProjectTreeBranchPostRequest = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/project/{username}/{project}/{build_num}',
    description=""" Full details for a single build. The response includes all of the fields from the build summary.
This is also the payload for the [notification webhooks](/docs/configuration/#notify), in which case this object is the value to a key named 'payload'.
 """,
    tags=['project_data_management', 'build_info_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def get_project__username__project__build_num(
    username: str, project: str = ..., build_num: int = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/project/{username}/{project}/{build_num}/artifacts',
    description=""" List the artifacts produced by a given build.
 """,
    tags=['user_management', 'project_data_management', 'build_info_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def get_project__username__project__build_num_artifacts(
    username: str, project: str = ..., build_num: int = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/project/{username}/{project}/{build_num}/cancel',
    description=""" Cancels the build, returns a summary of the build.
 """,
    tags=['project_data_management', 'build_info_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def post_project__username__project__build_num_cancel(
    username: str, project: str = ..., build_num: int = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/project/{username}/{project}/{build_num}/retry',
    description=""" Retries the build, returns a summary of the new build.
 """,
    tags=['project_data_management', 'build_info_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def post_project__username__project__build_num_retry(
    username: str, project: str = ..., build_num: int = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/project/{username}/{project}/{build_num}/tests',
    description=""" Provides test metadata for a build
Note: [Learn how to set up your builds to collect test metadata](https://circleci.com/docs/test-metadata/)
 """,
    tags=['project_data_management', 'build_info_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def get_project__username__project__build_num_tests(
    username: str, project: str = ..., build_num: int = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/projects',
    description=""" List of all the projects you're following on CircleCI, with build information organized by branch.
 """,
    tags=['user_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def get_projects():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recent-builds',
    description=""" Build summary for each of the last 30 recent builds, ordered by build_num.
 """,
    tags=['user_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def get_recent_builds(limit: Optional[conint(le=100)] = 30, offset: Optional[int] = 0):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/user/heroku-key',
    description=""" Adds your Heroku API key to CircleCI, takes apikey as form param name.
 """,
    tags=['user_management'],
    security=[
        APIKeyQuery(name="circle-token"),
    ],
)
def post_user_heroku_key():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
