# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T17:54:26+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, EmailStr, Field, RootModel


class Artifact(BaseModel):
    node_index: Optional[int] = None
    path: Optional[str] = None
    pretty_path: Optional[str] = None
    url: Optional[str] = None


class Artifacts(RootModel[List[Artifact]]):
    root: List[Artifact]


class Aws(BaseModel):
    keypair: Optional[str] = None


class BuildParameters(BaseModel):
    pass


class Envvar(BaseModel):
    name: Optional[str] = None
    value: Optional[str] = None


class Envvars(RootModel[List[Envvar]]):
    root: List[Envvar]


class Type(Enum):
    deploy_key = 'deploy-key'
    github_user_key = 'github-user-key'


class Key(BaseModel):
    fingerprint: Optional[str] = None
    preferred: Optional[bool] = None
    public_key: Optional[str] = None
    time: Optional[datetime] = Field(None, description='when the key was issued')
    type: Optional[Type] = Field(
        None, description='can be "deploy-key" or "github-user-key"\n'
    )


class Keys(RootModel[List[Key]]):
    root: List[Key]


class Lifecycle(Enum):
    queued = 'queued'
    scheduled = 'scheduled'
    not_run = 'not_run'
    not_running = 'not_running'
    running = 'running'
    finished = 'finished'


class Outcome(Enum):
    canceled = 'canceled'
    infrastructure_fail = 'infrastructure_fail'
    timedout = 'timedout'
    failed = 'failed'
    no_tests = 'no_tests'
    success = 'success'


class Parallel(RootModel[str]):
    root: str = Field(
        ...,
        description='The number of containers to use to run the build. Default is null and the project default is used.\n',
    )


class FeatureFlags(BaseModel):
    build_fork_prs: Optional[bool] = Field(None, alias='build-fork-prs')
    fleet: Optional[bool] = None
    junit: Optional[bool] = None
    oss: Optional[bool] = None
    osx: Optional[bool] = None
    set_github_status: Optional[bool] = Field(None, alias='set-github-status')
    trusty_beta: Optional[bool] = Field(None, alias='trusty-beta')


class Revision(RootModel[str]):
    root: str = Field(
        ...,
        description='The specific revision to build.\nDefault is null and the head of the branch is used. Cannot be used with tag parameter.\n',
    )


class Scope(Enum):
    write_settings = 'write-settings'
    view_builds = 'view-builds'
    read_settings = 'read-settings'
    trigger_builds = 'trigger-builds'
    all = 'all'
    status = 'status'
    none = 'none'


class Sha1(RootModel[str]):
    root: str


class Status(Enum):
    retried = 'retried'
    canceled = 'canceled'
    infrastructure_fail = 'infrastructure_fail'
    timedout = 'timedout'
    not_run = 'not_run'
    running = 'running'
    failed = 'failed'
    queued = 'queued'
    scheduled = 'scheduled'
    not_running = 'not_running'
    no_tests = 'no_tests'
    fixed = 'fixed'
    success = 'success'


class StringOrNull(RootModel[Optional[str]]):
    root: Optional[str] = None


class Tag(RootModel[str]):
    root: str = Field(
        ...,
        description='The tag to build. Default is null. Cannot be used with revision parameter.\n',
    )


class Test(BaseModel):
    classname: Optional[str] = None
    file: Optional[str] = None
    message: Optional[str] = None
    name: Optional[str] = None
    result: Optional[Status] = None
    run_time: Optional[float] = None
    source: Optional[str] = None


class Tests(BaseModel):
    tests: Optional[List[Test]] = None


class User(BaseModel):
    admin: Optional[bool] = None
    all_emails: Optional[List[EmailStr]] = None
    analytics_id: Optional[str] = None
    avatar_url: Optional[AnyUrl] = None
    basic_email_prefs: Optional[str] = None
    bitbucket: Optional[int] = None
    bitbucket_authorized: Optional[bool] = None
    containers: Optional[int] = None
    created_at: Optional[datetime] = None
    days_left_in_trial: Optional[int] = None
    dev_admin: Optional[bool] = None
    enrolled_betas: Optional[List[str]] = None
    github_id: Optional[int] = None
    github_oauth_scopes: Optional[List[str]] = None
    gravatar_id: Optional[int] = None
    heroku_api_key: Optional[str] = None
    in_beta_program: Optional[bool] = None
    login: Optional[str] = None
    name: Optional[str] = None
    organization_prefs: Optional[Dict[str, Any]] = None
    parallelism: Optional[int] = None
    plan: Optional[str] = None
    projects: Optional[Dict[str, Any]] = None
    pusher_id: Optional[str] = None
    selected_email: Optional[EmailStr] = None
    sign_in_count: Optional[int] = None
    trial_end: Optional[datetime] = None


class Filter(Enum):
    completed = 'completed'
    successful = 'successful'
    failed = 'failed'
    running = 'running'


class ProjectUsernameProjectPostRequest(BaseModel):
    build_parameters: Optional[BuildParameters] = None
    parallel: Optional[Parallel] = None
    revision: Optional[Revision] = None
    tag: Optional[Tag] = None


class ProjectUsernameProjectBuildCacheDeleteResponse(BaseModel):
    status: Optional[str] = None


class ProjectUsernameProjectCheckoutKeyPostRequest(Enum):
    deploy_key = 'deploy-key'
    github_user_key = 'github-user-key'


class Message(Enum):
    OK = 'OK'


class ProjectUsernameProjectCheckoutKeyFingerprintDeleteResponse(BaseModel):
    message: Optional[Message] = None


class ProjectUsernameProjectEnvvarNameDeleteResponse(BaseModel):
    message: Optional[Message] = None


class ProjectUsernameProjectSshKeyPostRequest(BaseModel):
    hostname: Optional[str] = None
    private_key: Optional[str] = None


class ProjectUsernameProjectSshKeyPostResponse(BaseModel):
    message: Optional[str] = None


class ContentType(Enum):
    application_json = 'application/json'


class ProjectUsernameProjectTreeBranchPostRequest(BaseModel):
    build_parameters: Optional[BuildParameters] = None
    parallel: Optional[Parallel] = None
    revision: Optional[Revision] = None


class UserHerokuKeyPostResponse(BaseModel):
    message: Optional[str] = None


class BuildSummary(BaseModel):
    added_at: Optional[datetime] = None
    build_num: Optional[int] = None
    outcome: Optional[Outcome] = None
    pushed_at: Optional[datetime] = None
    status: Optional[Status] = None
    vcs_revision: Optional[Sha1] = None


class CommitDetail(BaseModel):
    author_date: Optional[datetime] = None
    author_email: Optional[EmailStr] = None
    author_login: Optional[str] = None
    author_name: Optional[str] = None
    body: Optional[str] = None
    commit: Optional[Sha1] = None
    commit_url: Optional[AnyUrl] = None
    committer_date: Optional[datetime] = None
    committer_email: Optional[EmailStr] = None
    committer_login: Optional[str] = None
    committer_name: Optional[str] = None
    subject: Optional[str] = None


class CommitDetails(RootModel[List[CommitDetail]]):
    root: List[CommitDetail]


class PreviousBuild(BaseModel):
    build_num: Optional[int] = None
    build_time_millis: Optional[int] = None
    status: Optional[Status] = None


class Project(BaseModel):
    aws: Optional[Aws] = None
    branches: Optional[Dict[str, Any]] = None
    campfire_notify_prefs: Optional[StringOrNull] = None
    campfire_room: Optional[StringOrNull] = None
    campfire_subdomain: Optional[StringOrNull] = None
    campfire_token: Optional[StringOrNull] = None
    compile: Optional[str] = None
    default_branch: Optional[str] = None
    dependencies: Optional[str] = None
    extra: Optional[str] = None
    feature_flags: Optional[FeatureFlags] = None
    flowdock_api_token: Optional[StringOrNull] = None
    followed: Optional[bool] = None
    has_usable_key: Optional[bool] = None
    heroku_deploy_user: Optional[StringOrNull] = None
    hipchat_api_token: Optional[StringOrNull] = None
    hipchat_notify: Optional[StringOrNull] = None
    hipchat_notify_prefs: Optional[str] = None
    hipchat_room: Optional[StringOrNull] = None
    irc_channel: Optional[StringOrNull] = None
    irc_keyword: Optional[StringOrNull] = None
    irc_notify_prefs: Optional[StringOrNull] = None
    irc_password: Optional[StringOrNull] = None
    irc_server: Optional[StringOrNull] = None
    irc_username: Optional[StringOrNull] = None
    language: Optional[str] = None
    oss: Optional[bool] = None
    parallel: Optional[int] = None
    reponame: Optional[str] = None
    scopes: Optional[List[Scope]] = None
    setup: Optional[str] = None
    slack_api_token: Optional[StringOrNull] = None
    slack_channel: Optional[StringOrNull] = None
    slack_channel_override: Optional[StringOrNull] = None
    slack_notify_prefs: Optional[StringOrNull] = None
    slack_subdomain: Optional[StringOrNull] = None
    slack_webhook_url: Optional[AnyUrl] = None
    ssh_keys: Optional[List[str]] = None
    test: Optional[str] = None
    username: Optional[str] = None
    vcs_type: Optional[str] = None
    vcs_url: Optional[AnyUrl] = None


class Projects(RootModel[List[Project]]):
    root: List[Project]


class Build(BaseModel):
    body: Optional[str] = Field(None, description='commit message body')
    branch: Optional[str] = None
    build_time_millis: Optional[int] = None
    build_url: Optional[AnyUrl] = None
    committer_email: Optional[EmailStr] = None
    committer_name: Optional[str] = None
    dont_build: Optional[str] = Field(
        None, description="reason why we didn't build, if we didn't build"
    )
    lifecycle: Optional[Lifecycle] = None
    previous: Optional[PreviousBuild] = None
    queued_at: Optional[datetime] = Field(None, description='time build was queued')
    reponame: Optional[str] = None
    retry_of: Optional[int] = Field(
        None, description='build_num of the build this is a retry of'
    )
    start_time: Optional[datetime] = Field(None, description='time build started')
    stop_time: Optional[datetime] = Field(None, description='time build finished')
    subject: Optional[str] = None
    username: Optional[str] = None
    vcs_url: Optional[AnyUrl] = None
    why: Optional[str] = Field(
        None, description='short string explaining the reason we built'
    )


class BuildDetail(BaseModel):
    all_commit_details: Optional[CommitDetails] = None
    compare: Optional[AnyUrl] = None
    job_name: Optional[str] = None
    node: Optional[Any] = None
    previous_successful_build: Optional[PreviousBuild] = None
    retries: Optional[bool] = None
    ssh_enabled: Optional[bool] = None
    timedout: Optional[bool] = None
    usage_queued_at: Optional[datetime] = None
    user: Optional[User] = None


class Builds(RootModel[List[Build]]):
    root: List[Build]
